#cloud-config
package_update: true
packages:
  - docker.io
  - apt-transport-https
  - curl
  - kubeadm
  - kubelet
  - kubectl

runcmd:
  - systemctl enable docker && systemctl start docker
  # Initialize the master node; adjust the advertise address if needed.
  - kubeadm init --apiserver-advertise-address=$(hostname -I | awk '{print $1}') --pod-network-cidr=10.244.0.0/16
  - mkdir -p /root/.kube
  - cp /etc/kubernetes/admin.conf /root/.kube/config
  # Deploy a pod network (Flannel)
  - kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
